apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:3.5
          env:
            - name: NEO4J_AUTH
              value: "none"
            - name: NEO4J_dbms_memory_pagecache_size
              value: "1G"
            - name: NEO4J_dbms_memory_heap_initial__size
              value: "1G"
            - name: NEO4J_dbms_memory_heap_max__size
              value: "1G"
          ports:
            - containerPort: 7474
            - containerPort: 7687
