
services:
- name: docker:dind
  command: ["--insecure-registry=registry.local.vidoks.fr"]


- name: redis
- name: registry.local.vidoks.fr/epita-info8/info8
  alias: mongo
- name: neo4j

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: latest
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: root
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  REDIS_HOST: redis
  REDIS_PORT: 6379
  MONGO_HOST: mongo
  MONGO_PORT: 27017
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository

stages:
  - build
  - init
  - test


build_dind_maven:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    # Points the Docker client to the Docker daemon provided by docker:dind service
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    # Your registry URL (change accordingly)
    REGISTRY_URL: registry.local.vidoks.fr/epita-info8/info8
    # Full image name including registry, namespace, and tag
    IMAGE_NAME: registry.local.vidoks.fr/epita-info8/info8
  script:
    - cd epitweet-backend/docker/CI
    # Log in to your remote registry using CI environment variables
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    # Build the image using your Dockerfile in the repository root
    - docker build -t $IMAGE_NAME .
    # Push the built image to the registry
    - docker push $IMAGE_NAME

test:
  image: maven:3.8.3-openjdk-17
  stage: test
  script:
    - cd epitweet-backend/
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit: epitweet-backend/target/user-service/surefire-reports/*.xml
      junit: epitweet-backend/repo-post/target/surefire-reports/*
    paths:
      - epitweet-backend/target/*.jar
    expire_in: 1 week

