image: maven:3.8.3-openjdk-17

services:
  - docker:dind


variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd epitweet-backend/
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - epitweet-backend/target/*.jar
    expire_in: 1 week

test:
  stage: test

  script:
    - cd epitweet-backend/
    - mvn  test
  dependencies:
    - build
  artifacts:
    reports:
      junit: epitweet-backend/target/user-service/surefire-reports/*.xml
    paths:
      - epitweet-backend/target/*.jar
    expire_in: 1 week

