services:
 - name: docker:dind
   command: ["--tls=false"]

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

test:
 image: maven:3.9.9-amazoncorretto-17
 stage: test
 script:
  - cd epitweet-backend
  - mvn install
  - mvn test

