variables:
#  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  TESTCONTAINERS_HOST_OVERRIDE: localhost
test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-17-alpine
  services:
    - name: docker:24.0.5-dind
      command: ["--tls=false"]
  script:
    - cd epitweet-backend
    - mvn install
    - mvn test

