services:
 - name: docker:dind
   command: ["--tls=false"]

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

test:
 image: maven:3.9.9-eclipse-temurin-17-alpine
 stage: test
 script:
  - apk add --no-cache docker-cli
  - cd epitweet-backend
  - mvn install
  - mvn test

