variables:
  TESTCONTAINERS_HOST_OVERRIDE: "172.17.0.1"

test:
 image: maven:3.9.9-eclipse-temurin-17-alpine
 stage: test
 script:
  - apk update
  - apk add docker
  - cd epitweet-backend
  - mvn clean install
  - mvn test

