variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-17-alpine
  services:
    - name: docker:dind
      alias: docker
      command: ["--tls=false"]
  script:
    - apk update && apk add --no-cache docker
    - docker info
    - cd epitweet-backend
    - mvn install
    - mvn test

