---
apiVersion: v1
kind: Secret
metadata:
  name: epitweet-mongodb-credentials
stringData:
  SUNDALAND_MONGODB_USER: "admin"
  SUNDALAND_MONGODB_PASSWORD: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: epitweet-pull-secret
stringData:
  .dockerconfigjson: |
    {
      "auths": {
          "registry.cri.epita.fr": {
              "auth": "j2uMozgT3TazjFemeNDc"
          }
      }
    }
type: kubernetes.io/dockerconfigjson
