apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-timeline-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: home-timeline-service.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-timeline-service
                port:
                  number: 8086
