openapi: 3.0.3
info:
  title: user-service API
  version: 1.0.0-SNAPSHOT
paths:
  /api/users/auth:
    post:
      tags:
        - User Controller
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        "200":
          description: OK
  /api/users/create:
    post:
      tags:
        - User Controller
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        "200":
          description: OK
  /api/users/delete:
    delete:
      tags:
        - User Controller
      parameters:
        - name: userTag
          in: header
          schema:
            type: string
      responses:
        "200":
          description: OK
  /api/users/getUser:
    get:
      tags:
        - User Controller
      parameters:
        - name: userTag
          in: header
          schema:
            type: string
      responses:
        "200":
          description: OK
  /api/users/update:
    patch:
      tags:
        - User Controller
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        "200":
          description: OK
components:
  schemas:
    Date:
      format: date
      type: string
      example: 2022-03-10
    ObjectId:
      type: object
      properties:
        timestamp:
          format: int32
          type: integer
        counter:
          format: int32
          type: integer
        randomValue1:
          format: int32
          type: integer
        randomValue2:
          type: integer
        date:
          $ref: '#/components/schemas/Date'
    UserRequest:
      type: object
      properties:
        tag:
          type: string
        pseudo:
          type: string
        password:
          type: string
        blockedUsers:
          type: array
          items:
            $ref: '#/components/schemas/ObjectId'
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic