apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: search-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: search-service.local  # Remplacez par l'URL ou le domaine de votre choix
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: search-service
                port:
                  number: 8083

