apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repo-post
  template:
    metadata:
      labels:
        app: repo-post
    spec:
      containers:
        - name: repo-post
          image: registry.cri.epita.fr/ing/majeures/tc/info/student/2026/2025-epitweet-tinyx-03/repo-post # à adapter
          ports:
            - containerPort: 8082
          env:
            - name: QUARKUS_PROFILE
              value: prod
