apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: repo-post
spec:
  rules:
    - http:
       paths:
       - path: /api/posts
         pathType: Prefix
         backend:
          service:
            name: repo-post
            port:
              number: 8082
