apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-timeline-service
spec:
  rules:
    - http:
        paths:
          - path: /api/timeline/user
            pathType: Prefix
            backend:
              service:
                name: user-timeline-service
                port:
                  number: 8085