apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-timeline-service
spec:
  rules:
      - http:
         paths:
           - path: /api/timeline/home
             pathType: Prefix
             backend:
              service:
                name: home-timeline-service
                port:
                  number: 8086
